site_name: FastMCP Transport Guide
site_description: "A concise guide to FastMCP transports (stdio, http, sse) with code examples"
site_url: https://tnpaul.github.io/fastmcp-transport-guide/
repo_url: https://github.com/tnpaul/fastmcp-transport-guide

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo

nav:
  - Home: index.md