name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # Or any supported version

      # 3. Install MkDocs and dependencies
      - name: Install MkDocs and theme
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Debug mkdocs.yml
        run: |
          echo "==== mkdocs.yml ===="
          cat mkdocs.yml

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --clean --force
